kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
# This build config will create jenkins job and refer Jenkinsfile in repo then that jenkins file will refer actaul build config ( BuildConfig-Docker-Build-Strategy.yaml ) which will use docker build strategy 
# Once this created then it will be triggered if any changes happen in repo by using hello-java-spring-boot-ssh secret  
  name: hello-java-spring-boot-jenkinsstrategy-pipeline 
spec:
  nodeSelector: null
  output: {}
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'git@github.com:hsahu26/hello-java-spring-boot-dockerstrategy.git'
      ref: main
    sourceSecret:
      name: hello-java-spring-boot-ssh
  triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: AWQ91EZRjCoN-Q4expMR
  runPolicy: Serial
